export const REQUIRED_TEXT = "Field is required"
export const LIMIT_TEXT ="Fields max length is 50 characters"
export const DESCRIPTION_TEXT ="Fields max length is 250 characters"
export const ALPHA_TEXT ="Field accepts only alphabets "
export const EMAIL_TEXT ="Invalid E-mail"
export const ZIP_TEXT ="Invalid pincode" 
export const URL_TEXT ="Invalid website"
export const MOBILE_TEXT  ="Invalid mobile number"
export const PAN_TEXT ="Invalid PAN number"
export const GST_TEXT ="Invalid GST number"
export const MINMAX_TEXT ="Field must have value in between 1 to 6"
export const NUM_TEXT ="Field accepts only numeric values"
export const ADDRESS ="Invalid Address"

